# coding: utf-8

"""
    ShinJitsu API

    Document fraud detection API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from shinjitsu.models.scan_indicator_simple import ScanIndicatorSimple

class TestScanIndicatorSimple(unittest.TestCase):
    """ScanIndicatorSimple unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ScanIndicatorSimple:
        """Test ScanIndicatorSimple
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ScanIndicatorSimple`
        """
        model = ScanIndicatorSimple()
        if include_optional:
            return ScanIndicatorSimple(
                service = '',
                type = '',
                severity = 'low',
                score = 0.0,
                description = ''
            )
        else:
            return ScanIndicatorSimple(
                service = '',
                type = '',
                severity = 'low',
                score = 0.0,
                description = '',
        )
        """

    def testScanIndicatorSimple(self):
        """Test ScanIndicatorSimple"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
