# coding: utf-8

"""
    ShinJitsu API

    Document fraud detection API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from shinjitsu.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_scan_public_v1_scan_post(self) -> None:
        """Test case for scan_public_v1_scan_post

        Scan Public
        """
        pass


if __name__ == '__main__':
    unittest.main()
