# coding: utf-8

"""
    ShinJitsu API

    Document fraud detection API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from shinjitsu.api.analyze_api import AnalyzeApi


class TestAnalyzeApi(unittest.TestCase):
    """AnalyzeApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AnalyzeApi()

    def tearDown(self) -> None:
        pass

    def test_analyze_document_v1_analyze_post(self) -> None:
        """Test case for analyze_document_v1_analyze_post

        Analyze Document
        """
        pass


if __name__ == '__main__':
    unittest.main()
