# coding: utf-8

"""
    ShinJitsu API

    Document fraud detection API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from shinjitsu.models.analyze_response import AnalyzeResponse

class TestAnalyzeResponse(unittest.TestCase):
    """AnalyzeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AnalyzeResponse:
        """Test AnalyzeResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AnalyzeResponse`
        """
        model = AnalyzeResponse()
        if include_optional:
            return AnalyzeResponse(
                scan_id = '',
                risk_score = 1.337,
                verdict = '',
                indicators = [
                    shinjitsu.models.fraud_indicator.FraudIndicator(
                        service = '', 
                        type = '', 
                        severity = '', 
                        score = 1.337, 
                        description = '', )
                    ],
                summary = '',
                processing_time_ms = 56,
                file_name = '',
                file_type = ''
            )
        else:
            return AnalyzeResponse(
                scan_id = '',
                risk_score = 1.337,
                verdict = '',
                indicators = [
                    shinjitsu.models.fraud_indicator.FraudIndicator(
                        service = '', 
                        type = '', 
                        severity = '', 
                        score = 1.337, 
                        description = '', )
                    ],
                summary = '',
                processing_time_ms = 56,
                file_name = '',
                file_type = '',
        )
        """

    def testAnalyzeResponse(self):
        """Test AnalyzeResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
