# coding: utf-8

"""
    ShinJitsu API

    Document fraud detection API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from shinjitsu.models.src_controllers_v1_demo_fraud_indicator import SrcControllersV1DemoFraudIndicator

class TestSrcControllersV1DemoFraudIndicator(unittest.TestCase):
    """SrcControllersV1DemoFraudIndicator unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SrcControllersV1DemoFraudIndicator:
        """Test SrcControllersV1DemoFraudIndicator
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SrcControllersV1DemoFraudIndicator`
        """
        model = SrcControllersV1DemoFraudIndicator()
        if include_optional:
            return SrcControllersV1DemoFraudIndicator(
                service = '',
                type = '',
                severity = '',
                score = 1.337,
                description = ''
            )
        else:
            return SrcControllersV1DemoFraudIndicator(
                service = '',
                type = '',
                severity = '',
                score = 1.337,
                description = '',
        )
        """

    def testSrcControllersV1DemoFraudIndicator(self):
        """Test SrcControllersV1DemoFraudIndicator"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
