/* tslint:disable */
/* eslint-disable */
/**
 * ShinJitsu API
 * Document fraud detection API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SrcControllersV1AnalyzeFraudIndicator } from './SrcControllersV1AnalyzeFraudIndicator';
import {
    SrcControllersV1AnalyzeFraudIndicatorFromJSON,
    SrcControllersV1AnalyzeFraudIndicatorFromJSONTyped,
    SrcControllersV1AnalyzeFraudIndicatorToJSON,
    SrcControllersV1AnalyzeFraudIndicatorToJSONTyped,
} from './SrcControllersV1AnalyzeFraudIndicator';

/**
 * Response from document analysis.
 * @export
 * @interface AnalyzeResponse
 */
export interface AnalyzeResponse {
    /**
     * 
     * @type {string}
     * @memberof AnalyzeResponse
     */
    scanId: string;
    /**
     * 
     * @type {number}
     * @memberof AnalyzeResponse
     */
    riskScore: number;
    /**
     * 
     * @type {string}
     * @memberof AnalyzeResponse
     */
    verdict: string;
    /**
     * 
     * @type {Array<SrcControllersV1AnalyzeFraudIndicator>}
     * @memberof AnalyzeResponse
     */
    indicators: Array<SrcControllersV1AnalyzeFraudIndicator>;
    /**
     * 
     * @type {string}
     * @memberof AnalyzeResponse
     */
    summary: string;
    /**
     * 
     * @type {number}
     * @memberof AnalyzeResponse
     */
    processingTimeMs: number;
    /**
     * 
     * @type {string}
     * @memberof AnalyzeResponse
     */
    fileName: string;
    /**
     * 
     * @type {string}
     * @memberof AnalyzeResponse
     */
    fileType: string;
}

/**
 * Check if a given object implements the AnalyzeResponse interface.
 */
export function instanceOfAnalyzeResponse(value: object): value is AnalyzeResponse {
    if (!('scanId' in value) || value['scanId'] === undefined) return false;
    if (!('riskScore' in value) || value['riskScore'] === undefined) return false;
    if (!('verdict' in value) || value['verdict'] === undefined) return false;
    if (!('indicators' in value) || value['indicators'] === undefined) return false;
    if (!('summary' in value) || value['summary'] === undefined) return false;
    if (!('processingTimeMs' in value) || value['processingTimeMs'] === undefined) return false;
    if (!('fileName' in value) || value['fileName'] === undefined) return false;
    if (!('fileType' in value) || value['fileType'] === undefined) return false;
    return true;
}

export function AnalyzeResponseFromJSON(json: any): AnalyzeResponse {
    return AnalyzeResponseFromJSONTyped(json, false);
}

export function AnalyzeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalyzeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'scanId': json['scan_id'],
        'riskScore': json['risk_score'],
        'verdict': json['verdict'],
        'indicators': ((json['indicators'] as Array<any>).map(SrcControllersV1AnalyzeFraudIndicatorFromJSON)),
        'summary': json['summary'],
        'processingTimeMs': json['processing_time_ms'],
        'fileName': json['file_name'],
        'fileType': json['file_type'],
    };
}

export function AnalyzeResponseToJSON(json: any): AnalyzeResponse {
    return AnalyzeResponseToJSONTyped(json, false);
}

export function AnalyzeResponseToJSONTyped(value?: AnalyzeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'scan_id': value['scanId'],
        'risk_score': value['riskScore'],
        'verdict': value['verdict'],
        'indicators': ((value['indicators'] as Array<any>).map(SrcControllersV1AnalyzeFraudIndicatorToJSON)),
        'summary': value['summary'],
        'processing_time_ms': value['processingTimeMs'],
        'file_name': value['fileName'],
        'file_type': value['fileType'],
    };
}

