/* tslint:disable */
/* eslint-disable */
/**
 * ShinJitsu API
 * Document fraud detection API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A fraud indicator in simplified format for public API.
 * @export
 * @interface ScanIndicatorSimple
 */
export interface ScanIndicatorSimple {
    /**
     * Detection service name
     * @type {string}
     * @memberof ScanIndicatorSimple
     */
    service: string;
    /**
     * Type of detection
     * @type {string}
     * @memberof ScanIndicatorSimple
     */
    type: string;
    /**
     * Severity level
     * @type {string}
     * @memberof ScanIndicatorSimple
     */
    severity: ScanIndicatorSimpleSeverityEnum;
    /**
     * Detection score (0-1)
     * @type {number}
     * @memberof ScanIndicatorSimple
     */
    score: number;
    /**
     * Human-readable description
     * @type {string}
     * @memberof ScanIndicatorSimple
     */
    description: string;
}


/**
 * @export
 */
export const ScanIndicatorSimpleSeverityEnum = {
    Low: 'low',
    Medium: 'medium',
    High: 'high',
    Critical: 'critical'
} as const;
export type ScanIndicatorSimpleSeverityEnum = typeof ScanIndicatorSimpleSeverityEnum[keyof typeof ScanIndicatorSimpleSeverityEnum];


/**
 * Check if a given object implements the ScanIndicatorSimple interface.
 */
export function instanceOfScanIndicatorSimple(value: object): value is ScanIndicatorSimple {
    if (!('service' in value) || value['service'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('severity' in value) || value['severity'] === undefined) return false;
    if (!('score' in value) || value['score'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function ScanIndicatorSimpleFromJSON(json: any): ScanIndicatorSimple {
    return ScanIndicatorSimpleFromJSONTyped(json, false);
}

export function ScanIndicatorSimpleFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScanIndicatorSimple {
    if (json == null) {
        return json;
    }
    return {
        
        'service': json['service'],
        'type': json['type'],
        'severity': json['severity'],
        'score': json['score'],
        'description': json['description'],
    };
}

export function ScanIndicatorSimpleToJSON(json: any): ScanIndicatorSimple {
    return ScanIndicatorSimpleToJSONTyped(json, false);
}

export function ScanIndicatorSimpleToJSONTyped(value?: ScanIndicatorSimple | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'service': value['service'],
        'type': value['type'],
        'severity': value['severity'],
        'score': value['score'],
        'description': value['description'],
    };
}

