/* tslint:disable */
/* eslint-disable */
/**
 * ShinJitsu API
 * Document fraud detection API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ScanIndicatorSimple } from './ScanIndicatorSimple';
import {
    ScanIndicatorSimpleFromJSON,
    ScanIndicatorSimpleFromJSONTyped,
    ScanIndicatorSimpleToJSON,
    ScanIndicatorSimpleToJSONTyped,
} from './ScanIndicatorSimple';

/**
 * Response from POST /v1/scan - clean public API.
 * @export
 * @interface ScanResult
 */
export interface ScanResult {
    /**
     * Unique scan identifier
     * @type {string}
     * @memberof ScanResult
     */
    scanId: string;
    /**
     * Overall fraud assessment: clean, suspicious, fraudulent, not_applicable
     * @type {string}
     * @memberof ScanResult
     */
    verdict: string;
    /**
     * Risk score (0=clean, 1=fraud)
     * @type {number}
     * @memberof ScanResult
     */
    riskScore: number;
    /**
     * Fraud indicators found
     * @type {Array<ScanIndicatorSimple>}
     * @memberof ScanResult
     */
    indicators: Array<ScanIndicatorSimple>;
    /**
     * Human-readable summary
     * @type {string}
     * @memberof ScanResult
     */
    summary: string;
    /**
     * Processing time in milliseconds
     * @type {number}
     * @memberof ScanResult
     */
    processingTimeMs: number;
    /**
     * Original file name
     * @type {string}
     * @memberof ScanResult
     */
    fileName: string;
    /**
     * MIME type of uploaded file
     * @type {string}
     * @memberof ScanResult
     */
    fileType: string;
}

/**
 * Check if a given object implements the ScanResult interface.
 */
export function instanceOfScanResult(value: object): value is ScanResult {
    if (!('scanId' in value) || value['scanId'] === undefined) return false;
    if (!('verdict' in value) || value['verdict'] === undefined) return false;
    if (!('riskScore' in value) || value['riskScore'] === undefined) return false;
    if (!('indicators' in value) || value['indicators'] === undefined) return false;
    if (!('summary' in value) || value['summary'] === undefined) return false;
    if (!('processingTimeMs' in value) || value['processingTimeMs'] === undefined) return false;
    if (!('fileName' in value) || value['fileName'] === undefined) return false;
    if (!('fileType' in value) || value['fileType'] === undefined) return false;
    return true;
}

export function ScanResultFromJSON(json: any): ScanResult {
    return ScanResultFromJSONTyped(json, false);
}

export function ScanResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScanResult {
    if (json == null) {
        return json;
    }
    return {
        
        'scanId': json['scan_id'],
        'verdict': json['verdict'],
        'riskScore': json['risk_score'],
        'indicators': ((json['indicators'] as Array<any>).map(ScanIndicatorSimpleFromJSON)),
        'summary': json['summary'],
        'processingTimeMs': json['processing_time_ms'],
        'fileName': json['file_name'],
        'fileType': json['file_type'],
    };
}

export function ScanResultToJSON(json: any): ScanResult {
    return ScanResultToJSONTyped(json, false);
}

export function ScanResultToJSONTyped(value?: ScanResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'scan_id': value['scanId'],
        'verdict': value['verdict'],
        'risk_score': value['riskScore'],
        'indicators': ((value['indicators'] as Array<any>).map(ScanIndicatorSimpleToJSON)),
        'summary': value['summary'],
        'processing_time_ms': value['processingTimeMs'],
        'file_name': value['fileName'],
        'file_type': value['fileType'],
    };
}

