/* tslint:disable */
/* eslint-disable */
/**
 * ShinJitsu API
 * Document fraud detection API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A single fraud detection indicator.
 * @export
 * @interface SrcControllersV1DemoFraudIndicator
 */
export interface SrcControllersV1DemoFraudIndicator {
    /**
     * 
     * @type {string}
     * @memberof SrcControllersV1DemoFraudIndicator
     */
    service: string;
    /**
     * 
     * @type {string}
     * @memberof SrcControllersV1DemoFraudIndicator
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof SrcControllersV1DemoFraudIndicator
     */
    severity: string;
    /**
     * 
     * @type {number}
     * @memberof SrcControllersV1DemoFraudIndicator
     */
    score: number;
    /**
     * 
     * @type {string}
     * @memberof SrcControllersV1DemoFraudIndicator
     */
    description: string;
}

/**
 * Check if a given object implements the SrcControllersV1DemoFraudIndicator interface.
 */
export function instanceOfSrcControllersV1DemoFraudIndicator(value: object): value is SrcControllersV1DemoFraudIndicator {
    if (!('service' in value) || value['service'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('severity' in value) || value['severity'] === undefined) return false;
    if (!('score' in value) || value['score'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function SrcControllersV1DemoFraudIndicatorFromJSON(json: any): SrcControllersV1DemoFraudIndicator {
    return SrcControllersV1DemoFraudIndicatorFromJSONTyped(json, false);
}

export function SrcControllersV1DemoFraudIndicatorFromJSONTyped(json: any, ignoreDiscriminator: boolean): SrcControllersV1DemoFraudIndicator {
    if (json == null) {
        return json;
    }
    return {
        
        'service': json['service'],
        'type': json['type'],
        'severity': json['severity'],
        'score': json['score'],
        'description': json['description'],
    };
}

export function SrcControllersV1DemoFraudIndicatorToJSON(json: any): SrcControllersV1DemoFraudIndicator {
    return SrcControllersV1DemoFraudIndicatorToJSONTyped(json, false);
}

export function SrcControllersV1DemoFraudIndicatorToJSONTyped(value?: SrcControllersV1DemoFraudIndicator | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'service': value['service'],
        'type': value['type'],
        'severity': value['severity'],
        'score': value['score'],
        'description': value['description'],
    };
}

