/* tslint:disable */
/* eslint-disable */
/**
 * ShinJitsu API
 * Document fraud detection API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A single fraud detection indicator.
 * @export
 * @interface SrcControllersV1AnalyzeFraudIndicator
 */
export interface SrcControllersV1AnalyzeFraudIndicator {
    /**
     * 
     * @type {string}
     * @memberof SrcControllersV1AnalyzeFraudIndicator
     */
    service: string;
    /**
     * 
     * @type {string}
     * @memberof SrcControllersV1AnalyzeFraudIndicator
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof SrcControllersV1AnalyzeFraudIndicator
     */
    severity: string;
    /**
     * 
     * @type {number}
     * @memberof SrcControllersV1AnalyzeFraudIndicator
     */
    score: number;
    /**
     * 
     * @type {string}
     * @memberof SrcControllersV1AnalyzeFraudIndicator
     */
    description: string;
}

/**
 * Check if a given object implements the SrcControllersV1AnalyzeFraudIndicator interface.
 */
export function instanceOfSrcControllersV1AnalyzeFraudIndicator(value: object): value is SrcControllersV1AnalyzeFraudIndicator {
    if (!('service' in value) || value['service'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('severity' in value) || value['severity'] === undefined) return false;
    if (!('score' in value) || value['score'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function SrcControllersV1AnalyzeFraudIndicatorFromJSON(json: any): SrcControllersV1AnalyzeFraudIndicator {
    return SrcControllersV1AnalyzeFraudIndicatorFromJSONTyped(json, false);
}

export function SrcControllersV1AnalyzeFraudIndicatorFromJSONTyped(json: any, ignoreDiscriminator: boolean): SrcControllersV1AnalyzeFraudIndicator {
    if (json == null) {
        return json;
    }
    return {
        
        'service': json['service'],
        'type': json['type'],
        'severity': json['severity'],
        'score': json['score'],
        'description': json['description'],
    };
}

export function SrcControllersV1AnalyzeFraudIndicatorToJSON(json: any): SrcControllersV1AnalyzeFraudIndicator {
    return SrcControllersV1AnalyzeFraudIndicatorToJSONTyped(json, false);
}

export function SrcControllersV1AnalyzeFraudIndicatorToJSONTyped(value?: SrcControllersV1AnalyzeFraudIndicator | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'service': value['service'],
        'type': value['type'],
        'severity': value['severity'],
        'score': value['score'],
        'description': value['description'],
    };
}

