/*
ShinJitsu API

Document fraud detection API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package shinjitsu

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ScanIndicatorSimple type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScanIndicatorSimple{}

// ScanIndicatorSimple A fraud indicator in simplified format for public API.
type ScanIndicatorSimple struct {
	// Detection service name
	Service string `json:"service"`
	// Type of detection
	Type string `json:"type"`
	// Severity level
	Severity string `json:"severity"`
	// Detection score (0-1)
	Score float32 `json:"score"`
	// Human-readable description
	Description string `json:"description"`
}

type _ScanIndicatorSimple ScanIndicatorSimple

// NewScanIndicatorSimple instantiates a new ScanIndicatorSimple object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScanIndicatorSimple(service string, type_ string, severity string, score float32, description string) *ScanIndicatorSimple {
	this := ScanIndicatorSimple{}
	this.Service = service
	this.Type = type_
	this.Severity = severity
	this.Score = score
	this.Description = description
	return &this
}

// NewScanIndicatorSimpleWithDefaults instantiates a new ScanIndicatorSimple object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScanIndicatorSimpleWithDefaults() *ScanIndicatorSimple {
	this := ScanIndicatorSimple{}
	return &this
}

// GetService returns the Service field value
func (o *ScanIndicatorSimple) GetService() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Service
}

// GetServiceOk returns a tuple with the Service field value
// and a boolean to check if the value has been set.
func (o *ScanIndicatorSimple) GetServiceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Service, true
}

// SetService sets field value
func (o *ScanIndicatorSimple) SetService(v string) {
	o.Service = v
}

// GetType returns the Type field value
func (o *ScanIndicatorSimple) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ScanIndicatorSimple) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ScanIndicatorSimple) SetType(v string) {
	o.Type = v
}

// GetSeverity returns the Severity field value
func (o *ScanIndicatorSimple) GetSeverity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Severity
}

// GetSeverityOk returns a tuple with the Severity field value
// and a boolean to check if the value has been set.
func (o *ScanIndicatorSimple) GetSeverityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Severity, true
}

// SetSeverity sets field value
func (o *ScanIndicatorSimple) SetSeverity(v string) {
	o.Severity = v
}

// GetScore returns the Score field value
func (o *ScanIndicatorSimple) GetScore() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Score
}

// GetScoreOk returns a tuple with the Score field value
// and a boolean to check if the value has been set.
func (o *ScanIndicatorSimple) GetScoreOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Score, true
}

// SetScore sets field value
func (o *ScanIndicatorSimple) SetScore(v float32) {
	o.Score = v
}

// GetDescription returns the Description field value
func (o *ScanIndicatorSimple) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *ScanIndicatorSimple) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *ScanIndicatorSimple) SetDescription(v string) {
	o.Description = v
}

func (o ScanIndicatorSimple) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScanIndicatorSimple) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["service"] = o.Service
	toSerialize["type"] = o.Type
	toSerialize["severity"] = o.Severity
	toSerialize["score"] = o.Score
	toSerialize["description"] = o.Description
	return toSerialize, nil
}

func (o *ScanIndicatorSimple) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"service",
		"type",
		"severity",
		"score",
		"description",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varScanIndicatorSimple := _ScanIndicatorSimple{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varScanIndicatorSimple)

	if err != nil {
		return err
	}

	*o = ScanIndicatorSimple(varScanIndicatorSimple)

	return err
}

type NullableScanIndicatorSimple struct {
	value *ScanIndicatorSimple
	isSet bool
}

func (v NullableScanIndicatorSimple) Get() *ScanIndicatorSimple {
	return v.value
}

func (v *NullableScanIndicatorSimple) Set(val *ScanIndicatorSimple) {
	v.value = val
	v.isSet = true
}

func (v NullableScanIndicatorSimple) IsSet() bool {
	return v.isSet
}

func (v *NullableScanIndicatorSimple) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScanIndicatorSimple(val *ScanIndicatorSimple) *NullableScanIndicatorSimple {
	return &NullableScanIndicatorSimple{value: val, isSet: true}
}

func (v NullableScanIndicatorSimple) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScanIndicatorSimple) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


