/*
ShinJitsu API

Document fraud detection API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package shinjitsu

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AnalyzeResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AnalyzeResponse{}

// AnalyzeResponse Response from document analysis.
type AnalyzeResponse struct {
	ScanId string `json:"scan_id"`
	RiskScore float32 `json:"risk_score"`
	Verdict string `json:"verdict"`
	Indicators []SrcControllersV1AnalyzeFraudIndicator `json:"indicators"`
	Summary string `json:"summary"`
	ProcessingTimeMs int32 `json:"processing_time_ms"`
	FileName string `json:"file_name"`
	FileType string `json:"file_type"`
}

type _AnalyzeResponse AnalyzeResponse

// NewAnalyzeResponse instantiates a new AnalyzeResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAnalyzeResponse(scanId string, riskScore float32, verdict string, indicators []SrcControllersV1AnalyzeFraudIndicator, summary string, processingTimeMs int32, fileName string, fileType string) *AnalyzeResponse {
	this := AnalyzeResponse{}
	this.ScanId = scanId
	this.RiskScore = riskScore
	this.Verdict = verdict
	this.Indicators = indicators
	this.Summary = summary
	this.ProcessingTimeMs = processingTimeMs
	this.FileName = fileName
	this.FileType = fileType
	return &this
}

// NewAnalyzeResponseWithDefaults instantiates a new AnalyzeResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAnalyzeResponseWithDefaults() *AnalyzeResponse {
	this := AnalyzeResponse{}
	return &this
}

// GetScanId returns the ScanId field value
func (o *AnalyzeResponse) GetScanId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ScanId
}

// GetScanIdOk returns a tuple with the ScanId field value
// and a boolean to check if the value has been set.
func (o *AnalyzeResponse) GetScanIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ScanId, true
}

// SetScanId sets field value
func (o *AnalyzeResponse) SetScanId(v string) {
	o.ScanId = v
}

// GetRiskScore returns the RiskScore field value
func (o *AnalyzeResponse) GetRiskScore() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.RiskScore
}

// GetRiskScoreOk returns a tuple with the RiskScore field value
// and a boolean to check if the value has been set.
func (o *AnalyzeResponse) GetRiskScoreOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RiskScore, true
}

// SetRiskScore sets field value
func (o *AnalyzeResponse) SetRiskScore(v float32) {
	o.RiskScore = v
}

// GetVerdict returns the Verdict field value
func (o *AnalyzeResponse) GetVerdict() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Verdict
}

// GetVerdictOk returns a tuple with the Verdict field value
// and a boolean to check if the value has been set.
func (o *AnalyzeResponse) GetVerdictOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Verdict, true
}

// SetVerdict sets field value
func (o *AnalyzeResponse) SetVerdict(v string) {
	o.Verdict = v
}

// GetIndicators returns the Indicators field value
func (o *AnalyzeResponse) GetIndicators() []SrcControllersV1AnalyzeFraudIndicator {
	if o == nil {
		var ret []SrcControllersV1AnalyzeFraudIndicator
		return ret
	}

	return o.Indicators
}

// GetIndicatorsOk returns a tuple with the Indicators field value
// and a boolean to check if the value has been set.
func (o *AnalyzeResponse) GetIndicatorsOk() ([]SrcControllersV1AnalyzeFraudIndicator, bool) {
	if o == nil {
		return nil, false
	}
	return o.Indicators, true
}

// SetIndicators sets field value
func (o *AnalyzeResponse) SetIndicators(v []SrcControllersV1AnalyzeFraudIndicator) {
	o.Indicators = v
}

// GetSummary returns the Summary field value
func (o *AnalyzeResponse) GetSummary() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value
// and a boolean to check if the value has been set.
func (o *AnalyzeResponse) GetSummaryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Summary, true
}

// SetSummary sets field value
func (o *AnalyzeResponse) SetSummary(v string) {
	o.Summary = v
}

// GetProcessingTimeMs returns the ProcessingTimeMs field value
func (o *AnalyzeResponse) GetProcessingTimeMs() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ProcessingTimeMs
}

// GetProcessingTimeMsOk returns a tuple with the ProcessingTimeMs field value
// and a boolean to check if the value has been set.
func (o *AnalyzeResponse) GetProcessingTimeMsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProcessingTimeMs, true
}

// SetProcessingTimeMs sets field value
func (o *AnalyzeResponse) SetProcessingTimeMs(v int32) {
	o.ProcessingTimeMs = v
}

// GetFileName returns the FileName field value
func (o *AnalyzeResponse) GetFileName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FileName
}

// GetFileNameOk returns a tuple with the FileName field value
// and a boolean to check if the value has been set.
func (o *AnalyzeResponse) GetFileNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FileName, true
}

// SetFileName sets field value
func (o *AnalyzeResponse) SetFileName(v string) {
	o.FileName = v
}

// GetFileType returns the FileType field value
func (o *AnalyzeResponse) GetFileType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FileType
}

// GetFileTypeOk returns a tuple with the FileType field value
// and a boolean to check if the value has been set.
func (o *AnalyzeResponse) GetFileTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FileType, true
}

// SetFileType sets field value
func (o *AnalyzeResponse) SetFileType(v string) {
	o.FileType = v
}

func (o AnalyzeResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AnalyzeResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["scan_id"] = o.ScanId
	toSerialize["risk_score"] = o.RiskScore
	toSerialize["verdict"] = o.Verdict
	toSerialize["indicators"] = o.Indicators
	toSerialize["summary"] = o.Summary
	toSerialize["processing_time_ms"] = o.ProcessingTimeMs
	toSerialize["file_name"] = o.FileName
	toSerialize["file_type"] = o.FileType
	return toSerialize, nil
}

func (o *AnalyzeResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"scan_id",
		"risk_score",
		"verdict",
		"indicators",
		"summary",
		"processing_time_ms",
		"file_name",
		"file_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAnalyzeResponse := _AnalyzeResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAnalyzeResponse)

	if err != nil {
		return err
	}

	*o = AnalyzeResponse(varAnalyzeResponse)

	return err
}

type NullableAnalyzeResponse struct {
	value *AnalyzeResponse
	isSet bool
}

func (v NullableAnalyzeResponse) Get() *AnalyzeResponse {
	return v.value
}

func (v *NullableAnalyzeResponse) Set(val *AnalyzeResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAnalyzeResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAnalyzeResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAnalyzeResponse(val *AnalyzeResponse) *NullableAnalyzeResponse {
	return &NullableAnalyzeResponse{value: val, isSet: true}
}

func (v NullableAnalyzeResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAnalyzeResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


