/*
ShinJitsu API

Document fraud detection API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package shinjitsu

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SrcControllersV1AnalyzeFraudIndicator type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SrcControllersV1AnalyzeFraudIndicator{}

// SrcControllersV1AnalyzeFraudIndicator A single fraud detection indicator.
type SrcControllersV1AnalyzeFraudIndicator struct {
	Service string `json:"service"`
	Type string `json:"type"`
	Severity string `json:"severity"`
	Score float32 `json:"score"`
	Description string `json:"description"`
}

type _SrcControllersV1AnalyzeFraudIndicator SrcControllersV1AnalyzeFraudIndicator

// NewSrcControllersV1AnalyzeFraudIndicator instantiates a new SrcControllersV1AnalyzeFraudIndicator object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSrcControllersV1AnalyzeFraudIndicator(service string, type_ string, severity string, score float32, description string) *SrcControllersV1AnalyzeFraudIndicator {
	this := SrcControllersV1AnalyzeFraudIndicator{}
	this.Service = service
	this.Type = type_
	this.Severity = severity
	this.Score = score
	this.Description = description
	return &this
}

// NewSrcControllersV1AnalyzeFraudIndicatorWithDefaults instantiates a new SrcControllersV1AnalyzeFraudIndicator object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSrcControllersV1AnalyzeFraudIndicatorWithDefaults() *SrcControllersV1AnalyzeFraudIndicator {
	this := SrcControllersV1AnalyzeFraudIndicator{}
	return &this
}

// GetService returns the Service field value
func (o *SrcControllersV1AnalyzeFraudIndicator) GetService() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Service
}

// GetServiceOk returns a tuple with the Service field value
// and a boolean to check if the value has been set.
func (o *SrcControllersV1AnalyzeFraudIndicator) GetServiceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Service, true
}

// SetService sets field value
func (o *SrcControllersV1AnalyzeFraudIndicator) SetService(v string) {
	o.Service = v
}

// GetType returns the Type field value
func (o *SrcControllersV1AnalyzeFraudIndicator) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *SrcControllersV1AnalyzeFraudIndicator) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *SrcControllersV1AnalyzeFraudIndicator) SetType(v string) {
	o.Type = v
}

// GetSeverity returns the Severity field value
func (o *SrcControllersV1AnalyzeFraudIndicator) GetSeverity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Severity
}

// GetSeverityOk returns a tuple with the Severity field value
// and a boolean to check if the value has been set.
func (o *SrcControllersV1AnalyzeFraudIndicator) GetSeverityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Severity, true
}

// SetSeverity sets field value
func (o *SrcControllersV1AnalyzeFraudIndicator) SetSeverity(v string) {
	o.Severity = v
}

// GetScore returns the Score field value
func (o *SrcControllersV1AnalyzeFraudIndicator) GetScore() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Score
}

// GetScoreOk returns a tuple with the Score field value
// and a boolean to check if the value has been set.
func (o *SrcControllersV1AnalyzeFraudIndicator) GetScoreOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Score, true
}

// SetScore sets field value
func (o *SrcControllersV1AnalyzeFraudIndicator) SetScore(v float32) {
	o.Score = v
}

// GetDescription returns the Description field value
func (o *SrcControllersV1AnalyzeFraudIndicator) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *SrcControllersV1AnalyzeFraudIndicator) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *SrcControllersV1AnalyzeFraudIndicator) SetDescription(v string) {
	o.Description = v
}

func (o SrcControllersV1AnalyzeFraudIndicator) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SrcControllersV1AnalyzeFraudIndicator) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["service"] = o.Service
	toSerialize["type"] = o.Type
	toSerialize["severity"] = o.Severity
	toSerialize["score"] = o.Score
	toSerialize["description"] = o.Description
	return toSerialize, nil
}

func (o *SrcControllersV1AnalyzeFraudIndicator) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"service",
		"type",
		"severity",
		"score",
		"description",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSrcControllersV1AnalyzeFraudIndicator := _SrcControllersV1AnalyzeFraudIndicator{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSrcControllersV1AnalyzeFraudIndicator)

	if err != nil {
		return err
	}

	*o = SrcControllersV1AnalyzeFraudIndicator(varSrcControllersV1AnalyzeFraudIndicator)

	return err
}

type NullableSrcControllersV1AnalyzeFraudIndicator struct {
	value *SrcControllersV1AnalyzeFraudIndicator
	isSet bool
}

func (v NullableSrcControllersV1AnalyzeFraudIndicator) Get() *SrcControllersV1AnalyzeFraudIndicator {
	return v.value
}

func (v *NullableSrcControllersV1AnalyzeFraudIndicator) Set(val *SrcControllersV1AnalyzeFraudIndicator) {
	v.value = val
	v.isSet = true
}

func (v NullableSrcControllersV1AnalyzeFraudIndicator) IsSet() bool {
	return v.isSet
}

func (v *NullableSrcControllersV1AnalyzeFraudIndicator) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSrcControllersV1AnalyzeFraudIndicator(val *SrcControllersV1AnalyzeFraudIndicator) *NullableSrcControllersV1AnalyzeFraudIndicator {
	return &NullableSrcControllersV1AnalyzeFraudIndicator{value: val, isSet: true}
}

func (v NullableSrcControllersV1AnalyzeFraudIndicator) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSrcControllersV1AnalyzeFraudIndicator) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


