/* tslint:disable */
/* eslint-disable */
/**
 * ShinJitsu API
 * Document fraud detection API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AnalyzeResponse,
  HTTPValidationError,
} from '../models/index';
import {
    AnalyzeResponseFromJSON,
    AnalyzeResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface AnalyzeDocumentV1AnalyzePostRequest {
    authorization: string;
    file: Blob;
}

/**
 * 
 */
export class AnalyzeApi extends runtime.BaseAPI {

    /**
     * Analyze a document for fraud indicators.  Requires API token authentication via Authorization header: ``` Authorization: Bearer shj_your_api_token_here ```  Supported file types: - JPEG images (.jpg, .jpeg) - PNG images (.png) - PDF documents (.pdf)
     * Analyze Document
     */
    async analyzeDocumentV1AnalyzePostRaw(requestParameters: AnalyzeDocumentV1AnalyzePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AnalyzeResponse>> {
        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling analyzeDocumentV1AnalyzePost().'
            );
        }

        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling analyzeDocumentV1AnalyzePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }


        let urlPath = `/v1/analyze`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AnalyzeResponseFromJSON(jsonValue));
    }

    /**
     * Analyze a document for fraud indicators.  Requires API token authentication via Authorization header: ``` Authorization: Bearer shj_your_api_token_here ```  Supported file types: - JPEG images (.jpg, .jpeg) - PNG images (.png) - PDF documents (.pdf)
     * Analyze Document
     */
    async analyzeDocumentV1AnalyzePost(requestParameters: AnalyzeDocumentV1AnalyzePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AnalyzeResponse> {
        const response = await this.analyzeDocumentV1AnalyzePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
