/* tslint:disable */
/* eslint-disable */
/**
 * ShinJitsu API
 * Document fraud detection API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  ScanResult,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    ScanResultFromJSON,
    ScanResultToJSON,
} from '../models/index';

export interface ScanPublicV1ScanPostRequest {
    file: Blob;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Scan a document for fraud indicators.  Analyzes the uploaded document (PDF or image) and returns a fraud verdict with supporting indicators. Supports JPEG, PNG images and PDF documents.  **Authentication**: Supports two methods: - Clerk JWT: `Authorization: Bearer <clerk_jwt>` - API Token: `Authorization: Bearer shj_...`  **Data retention**: Uploaded files are automatically deleted after 24 hours.  Returns: - **scan_id**: Unique identifier for this scan - **verdict**: Overall assessment (clean, suspicious, fraudulent, not_applicable) - **risk_score**: Risk score from 0.0 (clean) to 1.0 (fraud) - **indicators**: List of fraud indicators found - **summary**: Human-readable summary  Returns 403 with SCAN_LIMIT_EXCEEDED if user has reached their limit.
     * Scan Public
     */
    async scanPublicV1ScanPostRaw(requestParameters: ScanPublicV1ScanPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ScanResult>> {
        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling scanPublicV1ScanPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }


        let urlPath = `/v1/scan`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ScanResultFromJSON(jsonValue));
    }

    /**
     * Scan a document for fraud indicators.  Analyzes the uploaded document (PDF or image) and returns a fraud verdict with supporting indicators. Supports JPEG, PNG images and PDF documents.  **Authentication**: Supports two methods: - Clerk JWT: `Authorization: Bearer <clerk_jwt>` - API Token: `Authorization: Bearer shj_...`  **Data retention**: Uploaded files are automatically deleted after 24 hours.  Returns: - **scan_id**: Unique identifier for this scan - **verdict**: Overall assessment (clean, suspicious, fraudulent, not_applicable) - **risk_score**: Risk score from 0.0 (clean) to 1.0 (fraud) - **indicators**: List of fraud indicators found - **summary**: Human-readable summary  Returns 403 with SCAN_LIMIT_EXCEEDED if user has reached their limit.
     * Scan Public
     */
    async scanPublicV1ScanPost(requestParameters: ScanPublicV1ScanPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ScanResult> {
        const response = await this.scanPublicV1ScanPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
