# coding: utf-8

# flake8: noqa
"""
    ShinJitsu API

    Document fraud detection API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from shinjitsu.models.analyze_response import AnalyzeResponse
from shinjitsu.models.http_validation_error import HTTPValidationError
from shinjitsu.models.src_controllers_v1_analyze_fraud_indicator import SrcControllersV1AnalyzeFraudIndicator
from shinjitsu.models.validation_error import ValidationError
from shinjitsu.models.validation_error_loc_inner import ValidationErrorLocInner

