# coding: utf-8

"""
    ShinJitsu API

    Document fraud detection API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Union
from shinjitsu.models.src_controllers_v1_analyze_fraud_indicator import SrcControllersV1AnalyzeFraudIndicator
from typing import Optional, Set
from typing_extensions import Self

class AnalyzeResponse(BaseModel):
    """
    Response from document analysis.
    """ # noqa: E501
    scan_id: StrictStr
    risk_score: Union[StrictFloat, StrictInt]
    verdict: StrictStr
    indicators: List[SrcControllersV1AnalyzeFraudIndicator]
    summary: StrictStr
    processing_time_ms: StrictInt
    file_name: StrictStr
    file_type: StrictStr
    __properties: ClassVar[List[str]] = ["scan_id", "risk_score", "verdict", "indicators", "summary", "processing_time_ms", "file_name", "file_type"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AnalyzeResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in indicators (list)
        _items = []
        if self.indicators:
            for _item_indicators in self.indicators:
                if _item_indicators:
                    _items.append(_item_indicators.to_dict())
            _dict['indicators'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AnalyzeResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "scan_id": obj.get("scan_id"),
            "risk_score": obj.get("risk_score"),
            "verdict": obj.get("verdict"),
            "indicators": [SrcControllersV1AnalyzeFraudIndicator.from_dict(_item) for _item in obj["indicators"]] if obj.get("indicators") is not None else None,
            "summary": obj.get("summary"),
            "processing_time_ms": obj.get("processing_time_ms"),
            "file_name": obj.get("file_name"),
            "file_type": obj.get("file_type")
        })
        return _obj


